#!/bin/bash

function error_msg() {
    local msg=$1
    test -z "$msg" && msg="Unknown error"
    echo "ERROR: $msg" >&2
    exit 1
}

function warn_msg() {
    local msg=$1
    test -z "$msg" && msg="Unknown error"
    echo "WARNING: $msg\n" >&2
}

function check_return_fail() {
    if [ $? -ne 0 ]; then
        fail_test "$1"
        return 0
    else
        return 1
    fi
}

function fail_test() {
    local reason=$1
    echo "${TEST}: FAIL - ${reason}"
    exit 1
}

function pass_test() {
    echo "${TEST}: PASS"
}

function check_root() {
    if [ $UID -eq 0 ]; then
        return 0
    else
        return 1
    fi
}
